# -*- coding: utf-8 -*-
"""checkpoint

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGd3AnZrXJrvXOb_dC1tbxugrJPlE20P
"""

print ("Welcome to Python world! Let's start coding")